name: "Issue 模板"
description: "请按照模板描述您的问题或建议，便于开发者快速定位和处理"

labels: ["需要处理", "等待回复"]

body:
  - types: [bug, feature, documentation, question, enhancement]
    description: "请选择问题类型"
    label: "类型"
    required: true

  - type: input
    id: title
    attributes:
      label: "简要描述"
      description: "用一句话概括您的问题/需求"
      placeholder: "例如：在IE11中计算精度异常"
    required: true

  - type: markdown
    attributes:
      label: "详细描述"
      description: "详细描述问题现象或需求背景"
    required: true

  - type: textarea
    id: steps
    attributes:
      label: "复现步骤"
      description: "描述如何复现问题（如果是新功能可填写使用场景）"
      placeholder: "1. 执行xxx操作\n2. 输入特定参数..."
    required: true

  - type: input
    id: expected
    attributes:
      label: "预期行为"
      description: "您期望看到的正确结果"
      placeholder: "例如：计算结果应保留两位小数"
    required: true

  - type: input
    id: actual
    attributes:
      label: "实际行为"
      description: "实际出现的结果（如果是新功能可写'N/A'）"
      placeholder: "例如：计算结果丢失精度，显示1.0000001"
    required: true

  - type: input
    id: version
    attributes:
      label: "版本信息"
      description: "请提供受影响的版本号"
      placeholder: "例如：v1.1.2 或 GitHub页面URL"
    required: true

  - type: input
    id: environment
    attributes:
      label: "环境信息"
      description: "操作系统、浏览器、Node.js版本等"
      placeholder: "例如：Windows 11 + Chrome 120 + Node.js 22"
    required: true

  - type: textarea
    id: additional
    attributes:
      label: "附加信息"
      description: "截图/日志/代码片段等辅助说明"
      placeholder: "粘贴错误日志、截图链接或相关代码片段"
    required: false

  - type: checkboxes
    id: checklists
    attributes:
      label: "提交前检查"
      options:
        - label: "已搜索现有issue未找到重复问题"
          required: true
        - label: "已阅读贡献指南（如有）"
          required: true
        - label: "提供完整上下文信息"
          required: true